
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xd3q\x1b\xb9I\x87|\xc2m\xc4b\xc5\x0e\x0b\xb7\xeb'
    
_lr_action_items = {'RIGHT':([2,6,10,11,14,16,17,],[-3,-8,-6,-5,17,-2,-4,]),'NAME':([0,3,5,8,9,13,],[1,10,10,10,10,10,]),'INT':([0,3,5,8,9,13,],[2,2,2,2,2,2,]),'PRINT':([0,],[5,]),'PLUS':([1,2,6,7,10,11,12,14,15,16,17,],[-6,-3,-8,13,-6,-5,13,13,13,-2,-4,]),'NEGATE':([0,3,5,8,9,13,],[3,3,3,3,3,3,]),'INPUT':([0,3,5,8,9,13,],[6,6,6,6,6,6,]),'$end':([1,2,4,6,7,10,11,12,15,16,17,],[-6,-3,0,-8,-9,-6,-5,-1,-7,-2,-4,]),'ASSIGN':([1,],[9,]),'LEFT':([0,3,5,8,9,13,],[8,8,8,8,8,8,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,3,5,8,9,13,],[7,11,12,14,15,16,]),'statement':([0,],[4,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> PRINT expression','statement',2,'p_print_statement','/home/evan/Dropbox/4555CS/p0/p0parse.py',42),
  ('expression -> expression PLUS expression','expression',3,'p_plus_expression','/home/evan/Dropbox/4555CS/p0/p0parse.py',45),
  ('expression -> INT','expression',1,'p_int_expression','/home/evan/Dropbox/4555CS/p0/p0parse.py',48),
  ('expression -> LEFT expression RIGHT','expression',3,'p_parentheses_expression','/home/evan/Dropbox/4555CS/p0/p0parse.py',53),
  ('expression -> NEGATE expression','expression',2,'p_negate_expression','/home/evan/Dropbox/4555CS/p0/p0parse.py',56),
  ('expression -> NAME','expression',1,'p_name_expression','/home/evan/Dropbox/4555CS/p0/p0parse.py',59),
  ('statement -> NAME ASSIGN expression','statement',3,'p_assign_statement','/home/evan/Dropbox/4555CS/p0/p0parse.py',62),
  ('expression -> INPUT','expression',1,'p_input_expression','/home/evan/Dropbox/4555CS/p0/p0parse.py',65),
  ('statement -> expression','statement',1,'p_discard_statement','/home/evan/Dropbox/4555CS/p0/p0parse.py',68),
]
